// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * State é a fase do updater, exibida pela UI.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * build de desenvolvimento
     */
    StateInactive = "inativo",
    StateIdle = "ocioso",
    StateChecking = "verificando",
    StateUpToDate = "em-dia",
    StateDownloading = "baixando",
    StateReady = "pronto",
    StateApplying = "aplicando",
    StateFailed = "falhou",
};

/**
 * Status é o que a UI recebe no evento update:status.
 */
export interface Status {
    "state": State;
    "current": string;
    "available": string;
    "notes": string[] | null;
    "done": number;
    "total": number;
    "error": string;
    "checkedAt": string;

    /**
     * resultado do último update aplicado
     */
    "message": string;
}
