// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * State é o estado observável de um serviço.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Stopped = "stopped",
    Starting = "starting",
    Ready = "ready",
    Degraded = "degraded",
    Stopping = "stopping",
    Failed = "failed",
};

/**
 * Status é o retrato serializável de um serviço (payload de service:state).
 */
export class Status {
    "id": string;
    "name": string;
    "group": string;
    "state": State;
    "pid": number;
    "port": number;
    "startedAt": string;
    "restarts": number;
    "lastError": string;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = State.$zero;
        }
        if (!("pid" in $$source)) {
            this["pid"] = 0;
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("restarts" in $$source)) {
            this["restarts"] = 0;
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status($$parsedSource as Partial<Status>);
    }
}
