// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * State é o estado observável de um serviço.
 */
export enum State {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Stopped = "stopped",
    Starting = "starting",
    Ready = "ready",
    Degraded = "degraded",
    Stopping = "stopping",
    Failed = "failed",
};

/**
 * Status é o retrato serializável de um serviço (payload de service:state).
 */
export interface Status {
    "id": string;
    "name": string;
    "group": string;
    "state": State;
    "pid": number;
    "port": number;
    "startedAt": string;
    "restarts": number;
    "lastError": string;
}
