// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Warning é um aviso não bloqueante mostrado na UI (evento stack:warnings).
 */
export interface Warning {
    /**
     * Code: "port-conflict" | "php-missing" | "htaccess-under-nginx" |
     * "wildcard-unavailable" | "wildcard-pending" | "hosts-pending" |
     * "ca-pending" | "tls-unavailable" | "web-missing" | "db-init-failed" |
     * "db-create-failed" | "proc-exe-missing"
     * 
     * "hosts-pending", "ca-pending" e "wildcard-pending" são as três pendências
     * que exigem UAC. O Reconcile só as reporta; a escrita fica em
     * Stack.ApplyHosts, Stack.InstallCA e Stack.ApplyWildcardDNS, disparadas
     * por botão — abrir o app não pede privilégio.
     */
    "code": string;
    "message": string;

    /**
     * "" quando global
     */
    "projectId": string;
}
