// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Warning é um aviso não bloqueante mostrado na UI (evento stack:warnings).
 */
export class Warning {
    /**
     * Code: "port-conflict" | "php-missing" | "htaccess-under-nginx" |
     * "wildcard-unavailable" | "hosts-pending" | "ca-pending" |
     * "tls-unavailable" | "web-missing" | "db-init-failed" |
     * "db-create-failed" | "proc-exe-missing"
     * 
     * "hosts-pending" e "ca-pending" são as duas pendências que exigem UAC. O
     * Reconcile só as reporta; a escrita fica em Stack.ApplyHosts e
     * Stack.InstallCA, disparadas por botão — abrir o app não pede privilégio.
     */
    "code": string;
    "message": string;

    /**
     * "" quando global
     */
    "projectId": string;

    /** Creates a new Warning instance. */
    constructor($$source: Partial<Warning> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("projectId" in $$source)) {
            this["projectId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Warning instance from a string or object.
     */
    static createFrom($$source: any = {}): Warning {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Warning($$parsedSource as Partial<Warning>);
    }
}
