// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Warning é um aviso não bloqueante mostrado na UI (evento stack:warnings).
 */
export interface Warning {
    /**
     * Code: "port-conflict" | "php-missing" | "htaccess-under-nginx" |
     * "wildcard-unavailable" | "elevation-denied" | "tls-unavailable" | "web-missing"
     */
    "code": string;
    "message": string;

    /**
     * "" quando global
     */
    "projectId": string;
}
