// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runtime$0 from "../runtime/models.js";

export interface Package {
    /**
     * "php-8.3.33-nts-vs16-x64"
     */
    "id": string;
    "kind": runtime$0.Kind;
    "version": string;
    "url": string;

    /**
     * hex minúsculo; "" = não verificar (evitar)
     */
    "sha256": string;
    "compiler": string;
    "arch": string;
    "notes": string;
}
