// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * State é o conteúdo de state.json. Campos ausentes no arquivo mantêm o valor de Default().
 */
export interface State {
    /**
     * 1
     */
    "schemaVersion": number;

    /**
     * default "apache"
     */
    "webServer": WebServerName;

    /**
     * "8.1"; vazio = maior instalada
     */
    "defaultPhp": string;

    /**
     * default 4
     */
    "poolSize": number;

    /**
     * 80
     */
    "httpPort": number;

    /**
     * 443
     */
    "httpsPort": number;

    /**
     * 3306
     */
    "mysqlPort": number;

    /**
     * 1025
     */
    "mailpitSmtpPort": number;

    /**
     * 8025
     */
    "mailpitHttpPort": number;

    /**
     * 8036
     */
    "phpMyAdminPort": number;

    /**
     * PhpMyAdminSecret é gerado uma vez e persistido: regerar a cada Reconcile
     * invalidaria a sessão aberta do usuário a cada mudança de projeto.
     */
    "phpMyAdminSecret": string;

    /**
     * diretórios-raiz de projetos
     */
    "roots": string[] | null;

    /**
     * "php:8.1" → portas reservadas
     */
    "portAlloc": { [_ in string]?: number[] | null } | null;

    /**
     * série "8.1" → extensões habilitadas; ausente = runtime.DefaultExtensions
     */
    "phpExtensions"?: { [_ in string]?: string[] | null } | null;

    /**
     * caminho do exe ou "" (usa `code`)
     */
    "editor": string;

    /**
     * "" = wt.exe se existir, senão cmd
     */
    "terminal": string;
    "sidebarCollapsed": boolean;
    "autostart": boolean;
}

/**
 * WebServerName identifica o web server ativo.
 */
export enum WebServerName {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Apache = "apache",
    Nginx = "nginx",
};
