// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * State é o conteúdo de state.json. Campos ausentes no arquivo mantêm o valor de Default().
 */
export class State {
    /**
     * 1
     */
    "schemaVersion": number;

    /**
     * default "apache"
     */
    "webServer": WebServerName;

    /**
     * "8.1"; vazio = maior instalada
     */
    "defaultPhp": string;

    /**
     * default 4
     */
    "poolSize": number;

    /**
     * 80
     */
    "httpPort": number;

    /**
     * 443
     */
    "httpsPort": number;

    /**
     * 3306
     */
    "mysqlPort": number;

    /**
     * 1025
     */
    "mailpitSmtpPort": number;

    /**
     * 8025
     */
    "mailpitHttpPort": number;

    /**
     * diretórios-raiz de projetos
     */
    "roots": string[];

    /**
     * "php:8.1" → portas reservadas
     */
    "portAlloc": { [_ in string]?: number[] };

    /**
     * série "8.1" → extensões habilitadas; ausente = runtime.DefaultExtensions
     */
    "phpExtensions"?: { [_ in string]?: string[] };

    /**
     * caminho do exe ou "" (usa `code`)
     */
    "editor": string;

    /**
     * "" = wt.exe se existir, senão cmd
     */
    "terminal": string;
    "sidebarCollapsed": boolean;
    "autostart": boolean;

    /** Creates a new State instance. */
    constructor($$source: Partial<State> = {}) {
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("webServer" in $$source)) {
            this["webServer"] = WebServerName.$zero;
        }
        if (!("defaultPhp" in $$source)) {
            this["defaultPhp"] = "";
        }
        if (!("poolSize" in $$source)) {
            this["poolSize"] = 0;
        }
        if (!("httpPort" in $$source)) {
            this["httpPort"] = 0;
        }
        if (!("httpsPort" in $$source)) {
            this["httpsPort"] = 0;
        }
        if (!("mysqlPort" in $$source)) {
            this["mysqlPort"] = 0;
        }
        if (!("mailpitSmtpPort" in $$source)) {
            this["mailpitSmtpPort"] = 0;
        }
        if (!("mailpitHttpPort" in $$source)) {
            this["mailpitHttpPort"] = 0;
        }
        if (!("roots" in $$source)) {
            this["roots"] = [];
        }
        if (!("portAlloc" in $$source)) {
            this["portAlloc"] = {};
        }
        if (!("editor" in $$source)) {
            this["editor"] = "";
        }
        if (!("terminal" in $$source)) {
            this["terminal"] = "";
        }
        if (!("sidebarCollapsed" in $$source)) {
            this["sidebarCollapsed"] = false;
        }
        if (!("autostart" in $$source)) {
            this["autostart"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     */
    static createFrom($$source: any = {}): State {
        const $$createField9_0 = $$createType0;
        const $$createField10_0 = $$createType2;
        const $$createField11_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("roots" in $$parsedSource) {
            $$parsedSource["roots"] = $$createField9_0($$parsedSource["roots"]);
        }
        if ("portAlloc" in $$parsedSource) {
            $$parsedSource["portAlloc"] = $$createField10_0($$parsedSource["portAlloc"]);
        }
        if ("phpExtensions" in $$parsedSource) {
            $$parsedSource["phpExtensions"] = $$createField11_0($$parsedSource["phpExtensions"]);
        }
        return new State($$parsedSource as Partial<State>);
    }
}

/**
 * WebServerName identifica o web server ativo.
 */
export enum WebServerName {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    Apache = "apache",
    Nginx = "nginx",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = $Create.Map($Create.Any, $$createType0);
