// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Project é um Manifest resolvido contra o disco.
 */
export class Project {
    "name": string;
    "domain": string;
    "wildcard": boolean;
    "php": string;
    "docroot": string;
    "extensions": string[];
    "database": string;
    "processes": { [_ in string]?: string };

    /**
     * NormalizeName(Name)
     */
    "id": string;

    /**
     * absoluto, limpo
     */
    "root": string;

    /**
     * hyphp.yaml existia
     */
    "hasManifest": boolean;

    /**
     * .htaccess em Root ou em DocrootAbs
     */
    "hasHtaccess": boolean;

    /**
     * Root ou Root/Docroot
     */
    "docrootAbs": string;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("domain" in $$source)) {
            this["domain"] = "";
        }
        if (!("wildcard" in $$source)) {
            this["wildcard"] = false;
        }
        if (!("php" in $$source)) {
            this["php"] = "";
        }
        if (!("docroot" in $$source)) {
            this["docroot"] = "";
        }
        if (!("extensions" in $$source)) {
            this["extensions"] = [];
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("processes" in $$source)) {
            this["processes"] = {};
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("root" in $$source)) {
            this["root"] = "";
        }
        if (!("hasManifest" in $$source)) {
            this["hasManifest"] = false;
        }
        if (!("hasHtaccess" in $$source)) {
            this["hasHtaccess"] = false;
        }
        if (!("docrootAbs" in $$source)) {
            this["docrootAbs"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        const $$createField5_0 = $$createType0;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("extensions" in $$parsedSource) {
            $$parsedSource["extensions"] = $$createField5_0($$parsedSource["extensions"]);
        }
        if ("processes" in $$parsedSource) {
            $$parsedSource["processes"] = $$createField7_0($$parsedSource["processes"]);
        }
        return new Project($$parsedSource as Partial<Project>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
