// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Project é um Manifest resolvido contra o disco.
 */
export interface Project {
    "name": string;
    "domain": string;
    "wildcard": boolean;
    "php": string;
    "docroot": string;
    "extensions": string[] | null;
    "database": string;
    "processes": { [_ in string]?: string } | null;

    /**
     * NormalizeName(Name)
     */
    "id": string;

    /**
     * absoluto, limpo
     */
    "root": string;

    /**
     * hyphp.yaml existia
     */
    "hasManifest": boolean;

    /**
     * .htaccess em Root ou em DocrootAbs
     */
    "hasHtaccess": boolean;

    /**
     * Root ou Root/Docroot
     */
    "docrootAbs": string;
}
