// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Extension {
    /**
     * "pdo_mysql"
     */
    "name": string;

    /**
     * "php_pdo_mysql.dll"
     */
    "file": string;
    "enabled": boolean;

    /** Creates a new Extension instance. */
    constructor($$source: Partial<Extension> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Extension instance from a string or object.
     */
    static createFrom($$source: any = {}): Extension {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Extension($$parsedSource as Partial<Extension>);
    }
}

export class Installed {
    "kind": Kind;

    /**
     * "8.1.10", "2.4.62", "1.26.2", "8.0.30"
     */
    "version": string;

    /**
     * PHP: "8.1"; outros: igual a Version
     */
    "major": string;

    /**
     * bin/php/php-8.1.10-Win32-vs16-x64 (absoluto)
     */
    "dir": string;

    /**
     * caminho absoluto do executável principal
     */
    "exe": string;

    /**
     * só PHP: php-cgi.exe
     */
    "cgiExe": string;

    /**
     * "vs16", "VC15", "VS17" ou ""
     */
    "compiler": string;

    /**
     * "x64" | "x86" | ""
     */
    "arch": string;

    /**
     * só PHP
     */
    "threadSafe": boolean | null;

    /** Creates a new Installed instance. */
    constructor($$source: Partial<Installed> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = Kind.$zero;
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("major" in $$source)) {
            this["major"] = "";
        }
        if (!("dir" in $$source)) {
            this["dir"] = "";
        }
        if (!("exe" in $$source)) {
            this["exe"] = "";
        }
        if (!("cgiExe" in $$source)) {
            this["cgiExe"] = "";
        }
        if (!("compiler" in $$source)) {
            this["compiler"] = "";
        }
        if (!("arch" in $$source)) {
            this["arch"] = "";
        }
        if (!("threadSafe" in $$source)) {
            this["threadSafe"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Installed instance from a string or object.
     */
    static createFrom($$source: any = {}): Installed {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Installed($$parsedSource as Partial<Installed>);
    }
}

export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PHP = "php",
    Apache = "apache",
    Nginx = "nginx",
    MySQL = "mysql",
    Mailpit = "mailpit",
    Mkcert = "mkcert",
};
