// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Extension {
    /**
     * "pdo_mysql"
     */
    "name": string;

    /**
     * "php_pdo_mysql.dll"
     */
    "file": string;
    "enabled": boolean;
}

export interface Installed {
    "kind": Kind;

    /**
     * "8.1.10", "2.4.62", "1.26.2", "8.0.30"
     */
    "version": string;

    /**
     * PHP: "8.1"; outros: igual a Version
     */
    "major": string;

    /**
     * bin/php/php-8.1.10-Win32-vs16-x64 (absoluto)
     */
    "dir": string;

    /**
     * caminho absoluto do executável principal
     */
    "exe": string;

    /**
     * só PHP: php-cgi.exe
     */
    "cgiExe": string;

    /**
     * "vs16", "VC15", "VS17" ou ""
     */
    "compiler": string;

    /**
     * "x64" | "x86" | ""
     */
    "arch": string;

    /**
     * só PHP
     */
    "threadSafe": boolean | null;

    /**
     * Formula é o nome de instalação no Homebrew ("shivammathur/php/php@8.3",
     * "httpd"); vazio no Windows e no que veio do catálogo. A remoção no Mac
     * usa este campo para decidir entre `brew uninstall` e apagar a pasta.
     */
    "formula"?: string;

    /**
     * Prefix é o prefixo do Homebrew que tem o keg (/opt/homebrew); vazio no
     * Windows. As configs do Mac leem dele o etc/ e o lib/ compartilhados.
     */
    "prefix"?: string;
}

export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    PHP = "php",
    Apache = "apache",
    Nginx = "nginx",
    MySQL = "mysql",
    MariaDB = "mariadb",
    Mailpit = "mailpit",
    Mkcert = "mkcert",
    PhpMyAdmin = "phpmyadmin",
};
