// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService expõe ações globais do app à UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * AddDefaultPHPToUserPath põe a série padrão de PHP no PATH do usuário, para
 * `php` e `composer` no terminal usarem a mesma versão que o HyPHP serve.
 */
export function AddDefaultPHPToUserPath(): $CancellablePromise<void> {
    return $Call.ByID(1092327310);
}

/**
 * OpenExternal abre uma URL http/https no browser padrão do Windows.
 */
export function OpenExternal(rawURL: string): $CancellablePromise<void> {
    return $Call.ByID(3248340690, rawURL);
}

/**
 * OpenFolder abre o diretório no Explorer.
 */
export function OpenFolder(path: string): $CancellablePromise<void> {
    return $Call.ByID(2950722645, path);
}

/**
 * OpenInEditor abre o caminho no editor configurado (state.Editor) ou no VS Code (`code`).
 */
export function OpenInEditor(path: string): $CancellablePromise<void> {
    return $Call.ByID(1066118839, path);
}

/**
 * OpenTerminal abre um terminal no diretório: state.Terminal, senão Windows Terminal, senão cmd.exe.
 */
export function OpenTerminal(path: string): $CancellablePromise<void> {
    return $Call.ByID(2005338537, path);
}

/**
 * Quit encerra o app de verdade (não apenas oculta a janela).
 */
export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(1055416018);
}

/**
 * RuntimeRoot retorna a raiz de runtime em uso (bin/, etc/, var/, log/).
 */
export function RuntimeRoot(): $CancellablePromise<string> {
    return $Call.ByID(3217706171);
}

/**
 * SiteURL retorna a página do HyPHP, a mesma citada no cabeçalho do
 * hyphp.yaml, para o Sobre de Configurações.
 */
export function SiteURL(): $CancellablePromise<string> {
    return $Call.ByID(3450115475);
}

/**
 * Version retorna a versão do HyPHP.
 */
export function Version(): $CancellablePromise<string> {
    return $Call.ByID(3568355387);
}
