// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CLIService escuta a CLI no pipe do usuário e serve a aba CLI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Activity devolve as chamadas recentes, a mais nova primeiro.
 */
export function Activity(): $CancellablePromise<$models.CLIActivity[] | null> {
    return $Call.ByID(2703919049);
}

/**
 * AddToPath põe a pasta da CLI no PATH do usuário: terminais abertos depois
 * disso acham `hyphp`.
 */
export function AddToPath(): $CancellablePromise<void> {
    return $Call.ByID(3884954041);
}

/**
 * Commands lista os comandos no idioma atual do app.
 */
export function Commands(): $CancellablePromise<$models.CLICommand[] | null> {
    return $Call.ByID(2003764970);
}

/**
 * Info devolve o estado da CLI para a aba.
 */
export function Info(): $CancellablePromise<$models.CLIInfo> {
    return $Call.ByID(2324722824);
}
