// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as supervisor$0 from "../internal/supervisor/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create cria um database vazio em utf8mb4. A validação de nome é a mesma do
 * Stack (mysqlcli.ValidateName), chamada dentro de Create.
 */
export function Create(name: string): $CancellablePromise<void> {
    return $Call.ByID(1295933745, name);
}

/**
 * Credentials é o acesso do servidor embutido: root sem senha em 127.0.0.1,
 * resultado do --initialize-insecure. É ambiente de desenvolvimento escutando
 * só em loopback; a senha vazia é decisão registrada, não descuido.
 */
export function Credentials(): $CancellablePromise<$models.Credentials> {
    return $Call.ByID(2739629349);
}

/**
 * Databases lista os schemas de usuário com tamanho em MB.
 */
export function Databases(): $CancellablePromise<$models.DBInfo[] | null> {
    return $Call.ByID(524346749);
}

/**
 * Drop remove um database de usuário; schemas de sistema são recusados pelo
 * mysqlcli.
 */
export function Drop(name: string): $CancellablePromise<void> {
    return $Call.ByID(2042209096, name);
}

/**
 * PhpMyAdminURL é a URL do vhost dedicado da ferramenta, ou "" quando ela não
 * está instalada. É "" em vez de erro porque a ausência não é falha: a UI usa
 * a string vazia para oferecer a instalação no lugar do botão de abrir.
 */
export function PhpMyAdminURL(): $CancellablePromise<string> {
    return $Call.ByID(3334924489);
}

/**
 * Status devolve o status do spec mysql. Se ele não existe (MySQL não
 * instalado), devolve um status stopped em vez de zero value — a UI precisa do
 * ID e do nome para desenhar a tela vazia.
 */
export function Status(): $CancellablePromise<supervisor$0.Status> {
    return $Call.ByID(230257251);
}
