// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogsService lista as origens de log. O conteúdo vai pelo stream "logs".
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Sources devolve um item por serviço registrado, na ordem de List().
 */
export function Sources(): $CancellablePromise<$models.LogSource[]> {
    return $Call.ByID(71870795).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.LogSource.createFrom;
const $$createType1 = $Create.Array($$createType0);
