// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogSource é uma origem de log oferecida à tela Logs.
 */
export interface LogSource {
    "id": string;
    "name": string;
    "group": string;
}
