// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CLIActivity é uma chamada recebida da CLI.
 */
export interface CLIActivity {
    "at": string;
    "command": string;
    "caller": string;
    "ok": boolean;
    "error": string;
    "durationMs": number;
}

/**
 * CLICommand é uma linha da lista de comandos da aba.
 */
export interface CLICommand {
    "usage": string;
    "description": string;
}

/**
 * CLIInfo é o estado que a aba CLI mostra.
 */
export interface CLIInfo {
    "address": string;
    "listening": boolean;
    "error": string;
    "exe": string;
    "exeExists": boolean;
    "onPath": boolean;
}

/**
 * Credentials é o que a UI mostra para montar a string de conexão (C18.7).
 * É struct, e não múltiplos retornos, porque o gerador de bindings TS não
 * representa mais de um valor não-erro.
 */
export interface Credentials {
    "user": string;
    "password": string;
    "host": string;
    "port": number;

    /**
     * Engine é o motor no ar ("mysql" ou "mariadb", vazio sem banco) e
     * Client o comando de linha do cliente dele, para o comando de conexão
     * que a tela mostra.
     */
    "engine": string;
    "client": string;
}

/**
 * DBInfo é a linha da tela Banco (C13).
 */
export interface DBInfo {
    "name": string;
    "sizeMb": number;
}

/**
 * IniSetting é uma linha do painel de php.ini: o valor efetivo da diretiva na
 * série e de onde ele vem.
 */
export interface IniSetting {
    "name": string;

    /**
     * o que vai valer nos workers
     */
    "value": string;

    /**
     * o que vale sem a escolha do usuário
     */
    "defaultValue": string;

    /**
     * "user" | "hyphp" | "php"
     */
    "source": string;
}

/**
 * LogSource é uma origem de log oferecida à tela Logs.
 */
export interface LogSource {
    "id": string;
    "name": string;
    "group": string;
}
