// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Credentials é o que a UI mostra para montar a string de conexão (C18.7).
 * É struct, e não múltiplos retornos, porque o gerador de bindings TS não
 * representa mais de um valor não-erro.
 */
export class Credentials {
    "user": string;
    "password": string;
    "host": string;
    "port": number;

    /** Creates a new Credentials instance. */
    constructor($$source: Partial<Credentials> = {}) {
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Credentials instance from a string or object.
     */
    static createFrom($$source: any = {}): Credentials {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Credentials($$parsedSource as Partial<Credentials>);
    }
}

/**
 * DBInfo é a linha da tela Banco (C13).
 */
export class DBInfo {
    "name": string;
    "sizeMb": number;

    /** Creates a new DBInfo instance. */
    constructor($$source: Partial<DBInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("sizeMb" in $$source)) {
            this["sizeMb"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DBInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DBInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DBInfo($$parsedSource as Partial<DBInfo>);
    }
}

/**
 * LogSource é uma origem de log oferecida à tela Logs.
 */
export class LogSource {
    "id": string;
    "name": string;
    "group": string;

    /** Creates a new LogSource instance. */
    constructor($$source: Partial<LogSource> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("group" in $$source)) {
            this["group"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogSource instance from a string or object.
     */
    static createFrom($$source: any = {}): LogSource {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogSource($$parsedSource as Partial<LogSource>);
    }
}
