// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProjectsService expõe projetos à UI. Toda mutação segue o mesmo caminho:
 * grava (state.json ou hyphp.yaml) → rescan → SetProjects → project:changed →
 * Reconcile. Serializado por mu: a UI pode disparar cliques em sequência.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "../internal/project/models.js";

export function AddRoot(dir: string): $CancellablePromise<void> {
    return $Call.ByID(4086019609, dir);
}

/**
 * CreateManifest materializa os defaults em hyphp.yaml. Idempotente.
 */
export function CreateManifest(id: string): $CancellablePromise<void> {
    return $Call.ByID(550577495, id);
}

export function List(): $CancellablePromise<project$0.Project[]> {
    return $Call.ByID(2443881030).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RemoveRoot(dir: string): $CancellablePromise<void> {
    return $Call.ByID(3127625210, dir);
}

/**
 * Rescan redescobre projetos e reconcilia. Também é o callback do Watcher.
 */
export function Rescan(): $CancellablePromise<void> {
    return $Call.ByID(1220673294);
}

export function Roots(): $CancellablePromise<string[]> {
    return $Call.ByID(1596131223).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SetPHP grava `php: "<major>"` no hyphp.yaml do projeto (criando-o se não
 * existir) e reconcilia. Não valida se a versão está instalada: o desired()
 * avisa php-missing e a UI oferece o download.
 */
export function SetPHP(id: string, major: string): $CancellablePromise<void> {
    return $Call.ByID(1413230758, id, major);
}

export function SetWildcard(id: string, on: boolean): $CancellablePromise<void> {
    return $Call.ByID(4166981656, id, on);
}

// Private type creation functions
const $$createType0 = project$0.Project.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
