// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pkgmgr$0 from "../internal/pkgmgr/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runtime$0 from "../internal/runtime/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Available devolve os pacotes do catálogo cuja (Kind, Version) não está instalada.
 */
export function Available(): $CancellablePromise<pkgmgr$0.Package[] | null> {
    return $Call.ByID(2942582160);
}

/**
 * CancelInstall interrompe o download em andamento do pacote. O progresso
 * termina com a fase "canceled" e o arquivo parcial é apagado. Depois do
 * download (verificação e extração, que levam segundos) não há o que cancelar.
 */
export function CancelInstall(packageID: string): $CancellablePromise<void> {
    return $Call.ByID(2726836002, packageID);
}

/**
 * Extensions lista os módulos do maior patch da série: os embutidos no binário
 * e os arquivos de ExtDir, marcando os habilitados.
 */
export function Extensions(major: string): $CancellablePromise<runtime$0.Extension[] | null> {
    return $Call.ByID(2025234643, major);
}

/**
 * ImportFrom copia para bin/ toda build reconhecível sob dir. Quem já tem PHP,
 * Apache ou MySQL na máquina não precisa rebaixar centenas de megabytes.
 */
export function ImportFrom(dir: string): $CancellablePromise<void> {
    return $Call.ByID(2554744644, dir);
}

/**
 * IniSettings lista as diretivas curadas e as que o usuário definiu para a
 * série, com valor efetivo, padrão e origem. Curadas primeiro, na ordem da
 * lista; depois as extras por nome.
 */
export function IniSettings(major: string): $CancellablePromise<$models.IniSetting[] | null> {
    return $Call.ByID(2495167728, major);
}

/**
 * Install dispara o download em goroutine. Progresso vai por download:progress;
 * ao terminar (com ou sem erro) faz Rescan, que emite runtime:changed.
 */
export function Install(packageID: string): $CancellablePromise<void> {
    return $Call.ByID(4006916488, packageID);
}

/**
 * Installed devolve o cache da última varredura (varre na primeira chamada).
 */
export function Installed(): $CancellablePromise<runtime$0.Installed[] | null> {
    return $Call.ByID(1071807753);
}

/**
 * PickImportDir abre o diálogo nativo de pasta. Cancelar devolve ("", nil) —
 * mesma comparação de mensagem de ProjectsService.PickRoot, pelo mesmo motivo
 * (cfd é interno ao Wails, não há sentinela importável).
 */
export function PickImportDir(): $CancellablePromise<string> {
    return $Call.ByID(3553219612);
}

/**
 * Remove para os serviços que rodam do runtime, apaga a pasta e revarre. A
 * revarredura dispara o Reconcile, que passa o serviço para outra versão
 * instalada ou o tira.
 */
export function Remove(kind: string, version: string): $CancellablePromise<void> {
    return $Call.ByID(476102805, kind, version);
}

/**
 * Rescan varre bin/, atualiza o cache e notifica (runtime:changed + OnChange).
 * Falhas parciais de detecção voltam no erro, mas o cache é atualizado mesmo assim.
 */
export function Rescan(): $CancellablePromise<void> {
    return $Call.ByID(1603836049);
}

/**
 * ResetIniSetting apaga a escolha do usuário; a diretiva volta ao padrão do
 * HyPHP ou do PHP. Sem diretivas, a série sai do mapa para o state.json não
 * acumular objetos vazios.
 */
export function ResetIniSetting(major: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(616363750, major, name);
}

/**
 * SetDefaultPHP grava state.DefaultPHP e notifica (settings:changed + runtime:changed).
 */
export function SetDefaultPHP(major: string): $CancellablePromise<void> {
    return $Call.ByID(2547105340, major);
}

/**
 * SetExtension liga/desliga uma extensão da série e persiste em state.PHPExtensions.
 * Embutida é recusada: está sempre ligada, e gravar o nome no state não muda
 * nada (o render só escreve extension= para módulo com arquivo).
 */
export function SetExtension(major: string, name: string, on: boolean): $CancellablePromise<void> {
    return $Call.ByID(3681623404, major, name, on);
}

/**
 * SetIniSetting define name=value no php.ini da série e persiste em
 * state.PHPIni. O Reconcile que o notify dispara regrava o php.ini e reinicia
 * só os workers dessa série.
 */
export function SetIniSetting(major: string, name: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(4262887465, major, name, value);
}
