// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ServicesService expõe a máquina de estados do supervisor à tela Serviços.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as supervisor$0 from "../internal/supervisor/models.js";

/**
 * List devolve todos os serviços ordenados por grupo e ID.
 */
export function List(): $CancellablePromise<supervisor$0.Status[] | null> {
    return $Call.ByID(694183796);
}

export function Restart(id: string): $CancellablePromise<void> {
    return $Call.ByID(2667201079, id);
}

/**
 * Start inicia um serviço. Devolve assim que o processo nasce; Ready ou
 * Failed chegam pelo evento service:state.
 */
export function Start(id: string): $CancellablePromise<void> {
    return $Call.ByID(4033425536, id);
}

export function StartAll(): $CancellablePromise<void> {
    return $Call.ByID(2736573139);
}

/**
 * Stop bloqueia até o serviço estar parado.
 */
export function Stop(id: string): $CancellablePromise<void> {
    return $Call.ByID(2357416004, id);
}

export function StopAll(): $CancellablePromise<void> {
    return $Call.ByID(1769778623);
}
