// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService lê e grava state.json via Stack e dispara Reconcile quando
 * algo que afeta processos/configs mudou.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as stack$0 from "../internal/stack/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as state$0 from "../internal/state/models.js";

export function Get(): $CancellablePromise<state$0.State> {
    return $Call.ByID(3443630107);
}

/**
 * Set aplica os campos editáveis. SchemaVersion e PortAlloc pertencem ao Stack
 * e são ignorados. Mudança de WebServer é delegada a SwitchWebServer depois de
 * gravar o resto (para a troca já usar as portas/pool novos).
 */
export function Set($in: state$0.State): $CancellablePromise<void> {
    return $Call.ByID(992415247, $in);
}

export function SwitchWebServer(name: string): $CancellablePromise<void> {
    return $Call.ByID(2073644598, name);
}

export function Warnings(): $CancellablePromise<stack$0.Warning[] | null> {
    return $Call.ByID(667350216);
}
