// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService lê e grava state.json via Stack e dispara Reconcile quando
 * algo que afeta processos/configs mudou.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as stack$0 from "../internal/stack/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as state$0 from "../internal/state/models.js";

/**
 * ApplyHosts grava os domínios dos projetos no arquivo hosts do Windows.
 * É a única ação do produto que pede UAC por causa de domínios, e existe como
 * ação explícita justamente para o app não exigir privilégio só para abrir:
 * o Reconcile apenas reporta o warning "hosts-pending", e a UI oferece o botão.
 */
export function ApplyHosts(): $CancellablePromise<void> {
    return $Call.ByID(4150864126);
}

/**
 * ApplyWildcardDNS registra a regra de DNS que faz *.dominio.test resolver.
 * Pede UAC, por isso é ação explícita: o Reconcile apenas reporta
 * "wildcard-pending".
 */
export function ApplyWildcardDNS(): $CancellablePromise<void> {
    return $Call.ByID(1410094740);
}

export function Get(): $CancellablePromise<state$0.State> {
    return $Call.ByID(3443630107);
}

/**
 * InstallCA instala o certificado raiz local, habilitando HTTPS nos sites.
 * Pede UAC, por isso é ação explícita: o Reconcile apenas reporta "ca-pending".
 */
export function InstallCA(): $CancellablePromise<void> {
    return $Call.ByID(701329380);
}

/**
 * Languages lista os idiomas oferecidos, na ordem da interface.
 */
export function Languages(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3207731188);
}

/**
 * RemoveWildcardDNS desfaz a regra. Sem esta porta, quem parasse de usar
 * wildcard ficaria com o namespace .test apontando para um resolvedor morto.
 */
export function RemoveWildcardDNS(): $CancellablePromise<void> {
    return $Call.ByID(3436439270);
}

/**
 * Set aplica os campos da tela Configurações. SchemaVersion e PortAlloc
 * pertencem ao Stack e são ignorados. Roots (ProjectsService),
 * PHPExtensions (RuntimesService), WebServer (SwitchWebServer, chamado
 * pelos cards da tela e por `hyphp web`) e DBEngine (SwitchDatabase) também
 * ficam de fora: são mudados por outros caminhos, e a cópia que a UI manda
 * pode ser anterior à mudança — gravá-la a desfaria (uma pasta recém-adicionada
 * sumia ao recolher a sidebar; um salvar qualquer trocava o web server de
 * volta). DefaultPHP fica: a tela tem o seletor "Versão padrão", e o rascunho
 * dela recebe o valor novo quando o Runtimes ou a CLI o trocam
 * (settings:changed).
 */
export function Set($in: state$0.State): $CancellablePromise<void> {
    return $Call.ByID(992415247, $in);
}

/**
 * SetSidebarCollapsed grava só o estado da sidebar. O toggle não pode passar
 * por Set: a cópia da UI levaria junto campos que outros serviços mudaram.
 */
export function SetSidebarCollapsed(collapsed: boolean): $CancellablePromise<void> {
    return $Call.ByID(3555457034, collapsed);
}

/**
 * SwitchDatabase troca o motor de banco (mysql|mariadb). Imediata, como a
 * troca de web server: o banco atual para e o outro sobe na mesma porta; se
 * o novo não ficar pronto, o anterior volta.
 */
export function SwitchDatabase(engine: string): $CancellablePromise<void> {
    return $Call.ByID(389183800, engine);
}

export function SwitchWebServer(name: string): $CancellablePromise<void> {
    return $Call.ByID(2073644598, name);
}

/**
 * SystemLanguage devolve o idioma que vale quando state.Language está vazio.
 * A UI pergunta ao Go, e não ao navigator do WebView, para os dois lados
 * escolherem igual.
 */
export function SystemLanguage(): $CancellablePromise<string> {
    return $Call.ByID(56439938);
}

export function Warnings(): $CancellablePromise<stack$0.Warning[] | null> {
    return $Call.ByID(667350216);
}
