// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateService expõe o auto-update à UI. O estado chega também pelo evento
 * update:status, emitido pelo próprio Updater a cada mudança.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as update$0 from "../internal/update/models.js";

/**
 * Apply fecha o app e instala a versão pronta. Se o atualizador não subir, o
 * erro volta e o app continua aberto.
 */
export function Apply(): $CancellablePromise<void> {
    return $Call.ByID(1848243923);
}

/**
 * Check verifica agora, independentemente do toggle automático.
 */
export function Check(): $CancellablePromise<void> {
    return $Call.ByID(2353891231);
}

/**
 * Status devolve o estado atual (a tela Sobre lê no primeiro render).
 */
export function Status(): $CancellablePromise<update$0.Status> {
    return $Call.ByID(2586545911);
}
